### ISSUE TITLE
Dino starve and dino breed in the config file does not work.

### ISSUE THREAD

**Issue by ErikC17Minecraft** [FossilsArcheologyRevival/FossilsArcheology1.7#349]
The Dino starve command prevent the from dying but still takes away the dinos under until they are at 0/xxx hunger.
The dino breed does not work, they breed anyway (so far Ive seen this on Deinonychus and Pteranodon.

**Comment by crakiMDH** [comment]
Wow... They closed the case without even telling you how to solve it... I'm having trouble with it too...

**Comment by lindstheginj** [comment]
That would be because its a glitch and you can't solve it. By "closing" it, that means that they've fixed the problem for the new patch.

**Comment by crakiMDH** [comment]
OK... Estimated time for 7.3.1 to come out?

**Comment by iLexiconn** [comment]
Should be fixed with llib 1.4.1

**Comment by crakiMDH** [comment]
So with Llibrary 1.4.1 for 1.7.10 the config bug is fixed?

**Comment by crakiMDH** [comment]
nvm, feathers still don't respond, and I'm seeing Gallimimus and Triceratops eating grass from time to time...
